[package]
name = "chip8"
version = "0.1.0"
authors = ["Roman Kolacz <roman@kolacz.io>"]

[dependencies]
rand = "0.5"
log = "0.4"
env_logger = "0.5.13"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]

